esphome:
  name: kiosk-display
  friendly_name: Kiosk Display

host:
  mac_address: "06:35:69:ab:f6:79"

api:

logger:

switch:
  - platform: template
    name: "Display Power"
    id: display_power
    icon: "mdi:monitor"
    optimistic: true
    turn_on_action:
      - lambda: |-
          int res = system("DISPLAY=:0 xset dpms force on");
    turn_off_action:
      - lambda: |-
          int res = system("DISPLAY=:0 xset dpms force off");

binary_sensor:
  - platform: homeassistant
    id: ha_motion_sensor
    entity_id: binary_sensor.motion_sensor
    on_press:
      then:
        - switch.turn_on: display_power
    on_release:
      then:
        - switch.turn_off: display_power
