apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bootc-dashboard-bootstrap
  description: Foundational early GitOps bootc base image configuration and automated build pipeline for host bootstrapping.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - bootc
    - gitops
    - centos-stream
    - kiosk
    - infrastructure
spec:
  type: service
  lifecycle: production
  owner: lanark-house
  domain: lanark-house
  system: kiosk-infrastructure
