name: Create Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Calculate SemVer & Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          noVersionBumpBehavior: patch
          noNewCommitBehavior: current

      - name: Create GitHub Release
        if: steps.semver.outputs.bump != 'none'
        uses: ncipollo/release-action@v1.16.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.semver.outputs.next }}
          name: ${{ steps.semver.outputs.next }}
          generateReleaseNotes: true
