name: Build Storybook

on:
  push:

jobs:
  build:
    name: Build Storybook Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Storybook Static Site
        run: pnpm run build-storybook

      - name: Upload Storybook Artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static-${{ github.sha }}
          path: ./storybook-static
          retention-days: 1
